//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Substrate.PolkadotBridgeHub.NET.RestClient.Mockup
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Substrate.PolkadotBridgeHub.NET.RestClient.Mockup.Generated.Interfaces;
   using Substrate.PolkadotBridgeHub.NET.RestClient.Mockup.Generated.Clients;
   
   public sealed class MockupClient
   {
      private HttpClient _httpClient;
      public IAuraControllerMockupClient AuraControllerClient;
      public IAuraExtControllerMockupClient AuraExtControllerClient;
      public IAuthorshipControllerMockupClient AuthorshipControllerClient;
      public IBalancesControllerMockupClient BalancesControllerClient;
      public IBridgeKusamaGrandpaControllerMockupClient BridgeKusamaGrandpaControllerClient;
      public IBridgeKusamaMessagesControllerMockupClient BridgeKusamaMessagesControllerClient;
      public IBridgeKusamaParachainsControllerMockupClient BridgeKusamaParachainsControllerClient;
      public IBridgeRelayersControllerMockupClient BridgeRelayersControllerClient;
      public ICollatorSelectionControllerMockupClient CollatorSelectionControllerClient;
      public IEthereumBeaconClientControllerMockupClient EthereumBeaconClientControllerClient;
      public IEthereumInboundQueueControllerMockupClient EthereumInboundQueueControllerClient;
      public IEthereumOutboundQueueControllerMockupClient EthereumOutboundQueueControllerClient;
      public IEthereumSystemControllerMockupClient EthereumSystemControllerClient;
      public IMessageQueueControllerMockupClient MessageQueueControllerClient;
      public IMultisigControllerMockupClient MultisigControllerClient;
      public IParachainInfoControllerMockupClient ParachainInfoControllerClient;
      public IParachainSystemControllerMockupClient ParachainSystemControllerClient;
      public IPolkadotXcmControllerMockupClient PolkadotXcmControllerClient;
      public ISessionControllerMockupClient SessionControllerClient;
      public ISystemControllerMockupClient SystemControllerClient;
      public ITimestampControllerMockupClient TimestampControllerClient;
      public ITransactionPaymentControllerMockupClient TransactionPaymentControllerClient;
      public IXcmpQueueControllerMockupClient XcmpQueueControllerClient;
      public MockupClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
         AuraControllerClient = new AuraControllerMockupClient(_httpClient);
         AuraExtControllerClient = new AuraExtControllerMockupClient(_httpClient);
         AuthorshipControllerClient = new AuthorshipControllerMockupClient(_httpClient);
         BalancesControllerClient = new BalancesControllerMockupClient(_httpClient);
         BridgeKusamaGrandpaControllerClient = new BridgeKusamaGrandpaControllerMockupClient(_httpClient);
         BridgeKusamaMessagesControllerClient = new BridgeKusamaMessagesControllerMockupClient(_httpClient);
         BridgeKusamaParachainsControllerClient = new BridgeKusamaParachainsControllerMockupClient(_httpClient);
         BridgeRelayersControllerClient = new BridgeRelayersControllerMockupClient(_httpClient);
         CollatorSelectionControllerClient = new CollatorSelectionControllerMockupClient(_httpClient);
         EthereumBeaconClientControllerClient = new EthereumBeaconClientControllerMockupClient(_httpClient);
         EthereumInboundQueueControllerClient = new EthereumInboundQueueControllerMockupClient(_httpClient);
         EthereumOutboundQueueControllerClient = new EthereumOutboundQueueControllerMockupClient(_httpClient);
         EthereumSystemControllerClient = new EthereumSystemControllerMockupClient(_httpClient);
         MessageQueueControllerClient = new MessageQueueControllerMockupClient(_httpClient);
         MultisigControllerClient = new MultisigControllerMockupClient(_httpClient);
         ParachainInfoControllerClient = new ParachainInfoControllerMockupClient(_httpClient);
         ParachainSystemControllerClient = new ParachainSystemControllerMockupClient(_httpClient);
         PolkadotXcmControllerClient = new PolkadotXcmControllerMockupClient(_httpClient);
         SessionControllerClient = new SessionControllerMockupClient(_httpClient);
         SystemControllerClient = new SystemControllerMockupClient(_httpClient);
         TimestampControllerClient = new TimestampControllerMockupClient(_httpClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerMockupClient(_httpClient);
         XcmpQueueControllerClient = new XcmpQueueControllerMockupClient(_httpClient);
      }
   }
}
