//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Substrate.Polkadot.NET.RestClient.Mockup
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Substrate.Polkadot.NET.RestClient.Mockup.Generated.Interfaces;
   using Substrate.Polkadot.NET.RestClient.Mockup.Generated.Clients;
   
   public sealed class MockupClient
   {
      private HttpClient _httpClient;
      public IAssetRateControllerMockupClient AssetRateControllerClient;
      public IAuctionsControllerMockupClient AuctionsControllerClient;
      public IAuthorityDiscoveryControllerMockupClient AuthorityDiscoveryControllerClient;
      public IAuthorshipControllerMockupClient AuthorshipControllerClient;
      public IBabeControllerMockupClient BabeControllerClient;
      public IBalancesControllerMockupClient BalancesControllerClient;
      public IBeefyControllerMockupClient BeefyControllerClient;
      public IBeefyMmrLeafControllerMockupClient BeefyMmrLeafControllerClient;
      public IBountiesControllerMockupClient BountiesControllerClient;
      public IChildBountiesControllerMockupClient ChildBountiesControllerClient;
      public IClaimsControllerMockupClient ClaimsControllerClient;
      public IConfigurationControllerMockupClient ConfigurationControllerClient;
      public IConvictionVotingControllerMockupClient ConvictionVotingControllerClient;
      public ICrowdloanControllerMockupClient CrowdloanControllerClient;
      public IDmpControllerMockupClient DmpControllerClient;
      public IElectionProviderMultiPhaseControllerMockupClient ElectionProviderMultiPhaseControllerClient;
      public IFastUnstakeControllerMockupClient FastUnstakeControllerClient;
      public IGrandpaControllerMockupClient GrandpaControllerClient;
      public IHistoricalControllerMockupClient HistoricalControllerClient;
      public IHrmpControllerMockupClient HrmpControllerClient;
      public IIdentityControllerMockupClient IdentityControllerClient;
      public IIndicesControllerMockupClient IndicesControllerClient;
      public IInitializerControllerMockupClient InitializerControllerClient;
      public IMessageQueueControllerMockupClient MessageQueueControllerClient;
      public IMmrControllerMockupClient MmrControllerClient;
      public IMultisigControllerMockupClient MultisigControllerClient;
      public INominationPoolsControllerMockupClient NominationPoolsControllerClient;
      public IOffencesControllerMockupClient OffencesControllerClient;
      public IParaInclusionControllerMockupClient ParaInclusionControllerClient;
      public IParaInherentControllerMockupClient ParaInherentControllerClient;
      public IParaSchedulerControllerMockupClient ParaSchedulerControllerClient;
      public IParasControllerMockupClient ParasControllerClient;
      public IParasDisputesControllerMockupClient ParasDisputesControllerClient;
      public IParaSessionInfoControllerMockupClient ParaSessionInfoControllerClient;
      public IParasSharedControllerMockupClient ParasSharedControllerClient;
      public IParasSlashingControllerMockupClient ParasSlashingControllerClient;
      public IPreimageControllerMockupClient PreimageControllerClient;
      public IProxyControllerMockupClient ProxyControllerClient;
      public IReferendaControllerMockupClient ReferendaControllerClient;
      public IRegistrarControllerMockupClient RegistrarControllerClient;
      public ISchedulerControllerMockupClient SchedulerControllerClient;
      public ISessionControllerMockupClient SessionControllerClient;
      public ISlotsControllerMockupClient SlotsControllerClient;
      public IStakingControllerMockupClient StakingControllerClient;
      public IStateTrieMigrationControllerMockupClient StateTrieMigrationControllerClient;
      public ISystemControllerMockupClient SystemControllerClient;
      public ITimestampControllerMockupClient TimestampControllerClient;
      public ITransactionPaymentControllerMockupClient TransactionPaymentControllerClient;
      public ITreasuryControllerMockupClient TreasuryControllerClient;
      public IVestingControllerMockupClient VestingControllerClient;
      public IVoterListControllerMockupClient VoterListControllerClient;
      public IWhitelistControllerMockupClient WhitelistControllerClient;
      public IXcmPalletControllerMockupClient XcmPalletControllerClient;
      public MockupClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
         AssetRateControllerClient = new AssetRateControllerMockupClient(_httpClient);
         AuctionsControllerClient = new AuctionsControllerMockupClient(_httpClient);
         AuthorityDiscoveryControllerClient = new AuthorityDiscoveryControllerMockupClient(_httpClient);
         AuthorshipControllerClient = new AuthorshipControllerMockupClient(_httpClient);
         BabeControllerClient = new BabeControllerMockupClient(_httpClient);
         BalancesControllerClient = new BalancesControllerMockupClient(_httpClient);
         BeefyControllerClient = new BeefyControllerMockupClient(_httpClient);
         BeefyMmrLeafControllerClient = new BeefyMmrLeafControllerMockupClient(_httpClient);
         BountiesControllerClient = new BountiesControllerMockupClient(_httpClient);
         ChildBountiesControllerClient = new ChildBountiesControllerMockupClient(_httpClient);
         ClaimsControllerClient = new ClaimsControllerMockupClient(_httpClient);
         ConfigurationControllerClient = new ConfigurationControllerMockupClient(_httpClient);
         ConvictionVotingControllerClient = new ConvictionVotingControllerMockupClient(_httpClient);
         CrowdloanControllerClient = new CrowdloanControllerMockupClient(_httpClient);
         DmpControllerClient = new DmpControllerMockupClient(_httpClient);
         ElectionProviderMultiPhaseControllerClient = new ElectionProviderMultiPhaseControllerMockupClient(_httpClient);
         FastUnstakeControllerClient = new FastUnstakeControllerMockupClient(_httpClient);
         GrandpaControllerClient = new GrandpaControllerMockupClient(_httpClient);
         HistoricalControllerClient = new HistoricalControllerMockupClient(_httpClient);
         HrmpControllerClient = new HrmpControllerMockupClient(_httpClient);
         IdentityControllerClient = new IdentityControllerMockupClient(_httpClient);
         IndicesControllerClient = new IndicesControllerMockupClient(_httpClient);
         InitializerControllerClient = new InitializerControllerMockupClient(_httpClient);
         MessageQueueControllerClient = new MessageQueueControllerMockupClient(_httpClient);
         MmrControllerClient = new MmrControllerMockupClient(_httpClient);
         MultisigControllerClient = new MultisigControllerMockupClient(_httpClient);
         NominationPoolsControllerClient = new NominationPoolsControllerMockupClient(_httpClient);
         OffencesControllerClient = new OffencesControllerMockupClient(_httpClient);
         ParaInclusionControllerClient = new ParaInclusionControllerMockupClient(_httpClient);
         ParaInherentControllerClient = new ParaInherentControllerMockupClient(_httpClient);
         ParaSchedulerControllerClient = new ParaSchedulerControllerMockupClient(_httpClient);
         ParasControllerClient = new ParasControllerMockupClient(_httpClient);
         ParasDisputesControllerClient = new ParasDisputesControllerMockupClient(_httpClient);
         ParaSessionInfoControllerClient = new ParaSessionInfoControllerMockupClient(_httpClient);
         ParasSharedControllerClient = new ParasSharedControllerMockupClient(_httpClient);
         ParasSlashingControllerClient = new ParasSlashingControllerMockupClient(_httpClient);
         PreimageControllerClient = new PreimageControllerMockupClient(_httpClient);
         ProxyControllerClient = new ProxyControllerMockupClient(_httpClient);
         ReferendaControllerClient = new ReferendaControllerMockupClient(_httpClient);
         RegistrarControllerClient = new RegistrarControllerMockupClient(_httpClient);
         SchedulerControllerClient = new SchedulerControllerMockupClient(_httpClient);
         SessionControllerClient = new SessionControllerMockupClient(_httpClient);
         SlotsControllerClient = new SlotsControllerMockupClient(_httpClient);
         StakingControllerClient = new StakingControllerMockupClient(_httpClient);
         StateTrieMigrationControllerClient = new StateTrieMigrationControllerMockupClient(_httpClient);
         SystemControllerClient = new SystemControllerMockupClient(_httpClient);
         TimestampControllerClient = new TimestampControllerMockupClient(_httpClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerMockupClient(_httpClient);
         TreasuryControllerClient = new TreasuryControllerMockupClient(_httpClient);
         VestingControllerClient = new VestingControllerMockupClient(_httpClient);
         VoterListControllerClient = new VoterListControllerMockupClient(_httpClient);
         WhitelistControllerClient = new WhitelistControllerMockupClient(_httpClient);
         XcmPalletControllerClient = new XcmPalletControllerMockupClient(_httpClient);
      }
   }
}
