//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Substrate.Moonsama.NET.RestClient
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Substrate.Moonsama.NET.RestClient.Generated.Interfaces;
   using Substrate.Moonsama.NET.RestClient.Generated.Clients;
   
   public sealed class Client
   {
      private HttpClient _httpClient;
      private BaseSubscriptionClient _subscriptionClient;
      public IAssetManagerControllerClient AssetManagerControllerClient;
      public IAssetsControllerClient AssetsControllerClient;
      public IAuraControllerClient AuraControllerClient;
      public IAuraExtControllerClient AuraExtControllerClient;
      public IAuthorshipControllerClient AuthorshipControllerClient;
      public IBalancesControllerClient BalancesControllerClient;
      public IContractsControllerClient ContractsControllerClient;
      public ICrowdloanRewardsControllerClient CrowdloanRewardsControllerClient;
      public IDmpQueueControllerClient DmpQueueControllerClient;
      public IEthereumControllerClient EthereumControllerClient;
      public IEvmChainIdControllerClient EvmChainIdControllerClient;
      public IEVMControllerClient EVMControllerClient;
      public IFreeCallsRegistryControllerClient FreeCallsRegistryControllerClient;
      public IIdentityControllerClient IdentityControllerClient;
      public ILocalAssetsControllerClient LocalAssetsControllerClient;
      public IMaintenanceModeControllerClient MaintenanceModeControllerClient;
      public IMintingControllerClient MintingControllerClient;
      public IMultisigControllerClient MultisigControllerClient;
      public IMultiTokenControllerClient MultiTokenControllerClient;
      public IParachainInfoControllerClient ParachainInfoControllerClient;
      public IParachainStakingControllerClient ParachainStakingControllerClient;
      public IParachainSystemControllerClient ParachainSystemControllerClient;
      public IPreimageControllerClient PreimageControllerClient;
      public IProxyControllerClient ProxyControllerClient;
      public IRandomnessControllerClient RandomnessControllerClient;
      public IRolesManagementControllerClient RolesManagementControllerClient;
      public ISchedulerControllerClient SchedulerControllerClient;
      public ISessionControllerClient SessionControllerClient;
      public ISudoControllerClient SudoControllerClient;
      public ISystemControllerClient SystemControllerClient;
      public ITimestampControllerClient TimestampControllerClient;
      public ITransactionPaymentControllerClient TransactionPaymentControllerClient;
      public ITreasuryControllerClient TreasuryControllerClient;
      public IXcmpQueueControllerClient XcmpQueueControllerClient;
      public IXTokensControllerClient XTokensControllerClient;
      public Client(HttpClient httpClient, BaseSubscriptionClient subscriptionClient)
      {
         _httpClient = httpClient;
         _subscriptionClient = subscriptionClient;
         AssetManagerControllerClient = new AssetManagerControllerClient(_httpClient, _subscriptionClient);
         AssetsControllerClient = new AssetsControllerClient(_httpClient, _subscriptionClient);
         AuraControllerClient = new AuraControllerClient(_httpClient, _subscriptionClient);
         AuraExtControllerClient = new AuraExtControllerClient(_httpClient, _subscriptionClient);
         AuthorshipControllerClient = new AuthorshipControllerClient(_httpClient, _subscriptionClient);
         BalancesControllerClient = new BalancesControllerClient(_httpClient, _subscriptionClient);
         ContractsControllerClient = new ContractsControllerClient(_httpClient, _subscriptionClient);
         CrowdloanRewardsControllerClient = new CrowdloanRewardsControllerClient(_httpClient, _subscriptionClient);
         DmpQueueControllerClient = new DmpQueueControllerClient(_httpClient, _subscriptionClient);
         EthereumControllerClient = new EthereumControllerClient(_httpClient, _subscriptionClient);
         EvmChainIdControllerClient = new EvmChainIdControllerClient(_httpClient, _subscriptionClient);
         EVMControllerClient = new EVMControllerClient(_httpClient, _subscriptionClient);
         FreeCallsRegistryControllerClient = new FreeCallsRegistryControllerClient(_httpClient, _subscriptionClient);
         IdentityControllerClient = new IdentityControllerClient(_httpClient, _subscriptionClient);
         LocalAssetsControllerClient = new LocalAssetsControllerClient(_httpClient, _subscriptionClient);
         MaintenanceModeControllerClient = new MaintenanceModeControllerClient(_httpClient, _subscriptionClient);
         MintingControllerClient = new MintingControllerClient(_httpClient, _subscriptionClient);
         MultisigControllerClient = new MultisigControllerClient(_httpClient, _subscriptionClient);
         MultiTokenControllerClient = new MultiTokenControllerClient(_httpClient, _subscriptionClient);
         ParachainInfoControllerClient = new ParachainInfoControllerClient(_httpClient, _subscriptionClient);
         ParachainStakingControllerClient = new ParachainStakingControllerClient(_httpClient, _subscriptionClient);
         ParachainSystemControllerClient = new ParachainSystemControllerClient(_httpClient, _subscriptionClient);
         PreimageControllerClient = new PreimageControllerClient(_httpClient, _subscriptionClient);
         ProxyControllerClient = new ProxyControllerClient(_httpClient, _subscriptionClient);
         RandomnessControllerClient = new RandomnessControllerClient(_httpClient, _subscriptionClient);
         RolesManagementControllerClient = new RolesManagementControllerClient(_httpClient, _subscriptionClient);
         SchedulerControllerClient = new SchedulerControllerClient(_httpClient, _subscriptionClient);
         SessionControllerClient = new SessionControllerClient(_httpClient, _subscriptionClient);
         SudoControllerClient = new SudoControllerClient(_httpClient, _subscriptionClient);
         SystemControllerClient = new SystemControllerClient(_httpClient, _subscriptionClient);
         TimestampControllerClient = new TimestampControllerClient(_httpClient, _subscriptionClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerClient(_httpClient, _subscriptionClient);
         TreasuryControllerClient = new TreasuryControllerClient(_httpClient, _subscriptionClient);
         XcmpQueueControllerClient = new XcmpQueueControllerClient(_httpClient, _subscriptionClient);
         XTokensControllerClient = new XTokensControllerClient(_httpClient, _subscriptionClient);
      }
   }
}
