//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Substrate.Collectives.NET.RestClient.Mockup
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Substrate.Collectives.NET.RestClient.Mockup.Generated.Interfaces;
   using Substrate.Collectives.NET.RestClient.Mockup.Generated.Clients;
   
   public sealed class MockupClient
   {
      private HttpClient _httpClient;
      public IAllianceControllerMockupClient AllianceControllerClient;
      public IAllianceMotionControllerMockupClient AllianceMotionControllerClient;
      public IAuraControllerMockupClient AuraControllerClient;
      public IAuraExtControllerMockupClient AuraExtControllerClient;
      public IAuthorshipControllerMockupClient AuthorshipControllerClient;
      public IBalancesControllerMockupClient BalancesControllerClient;
      public ICollatorSelectionControllerMockupClient CollatorSelectionControllerClient;
      public IDmpQueueControllerMockupClient DmpQueueControllerClient;
      public IFellowshipCollectiveControllerMockupClient FellowshipCollectiveControllerClient;
      public IFellowshipReferendaControllerMockupClient FellowshipReferendaControllerClient;
      public IMultisigControllerMockupClient MultisigControllerClient;
      public IParachainInfoControllerMockupClient ParachainInfoControllerClient;
      public IParachainSystemControllerMockupClient ParachainSystemControllerClient;
      public IPolkadotXcmControllerMockupClient PolkadotXcmControllerClient;
      public IPreimageControllerMockupClient PreimageControllerClient;
      public IProxyControllerMockupClient ProxyControllerClient;
      public ISchedulerControllerMockupClient SchedulerControllerClient;
      public ISessionControllerMockupClient SessionControllerClient;
      public ISystemControllerMockupClient SystemControllerClient;
      public ITimestampControllerMockupClient TimestampControllerClient;
      public ITransactionPaymentControllerMockupClient TransactionPaymentControllerClient;
      public IXcmpQueueControllerMockupClient XcmpQueueControllerClient;
      public MockupClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
         AllianceControllerClient = new AllianceControllerMockupClient(_httpClient);
         AllianceMotionControllerClient = new AllianceMotionControllerMockupClient(_httpClient);
         AuraControllerClient = new AuraControllerMockupClient(_httpClient);
         AuraExtControllerClient = new AuraExtControllerMockupClient(_httpClient);
         AuthorshipControllerClient = new AuthorshipControllerMockupClient(_httpClient);
         BalancesControllerClient = new BalancesControllerMockupClient(_httpClient);
         CollatorSelectionControllerClient = new CollatorSelectionControllerMockupClient(_httpClient);
         DmpQueueControllerClient = new DmpQueueControllerMockupClient(_httpClient);
         FellowshipCollectiveControllerClient = new FellowshipCollectiveControllerMockupClient(_httpClient);
         FellowshipReferendaControllerClient = new FellowshipReferendaControllerMockupClient(_httpClient);
         MultisigControllerClient = new MultisigControllerMockupClient(_httpClient);
         ParachainInfoControllerClient = new ParachainInfoControllerMockupClient(_httpClient);
         ParachainSystemControllerClient = new ParachainSystemControllerMockupClient(_httpClient);
         PolkadotXcmControllerClient = new PolkadotXcmControllerMockupClient(_httpClient);
         PreimageControllerClient = new PreimageControllerMockupClient(_httpClient);
         ProxyControllerClient = new ProxyControllerMockupClient(_httpClient);
         SchedulerControllerClient = new SchedulerControllerMockupClient(_httpClient);
         SessionControllerClient = new SessionControllerMockupClient(_httpClient);
         SystemControllerClient = new SystemControllerMockupClient(_httpClient);
         TimestampControllerClient = new TimestampControllerMockupClient(_httpClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerMockupClient(_httpClient);
         XcmpQueueControllerClient = new XcmpQueueControllerMockupClient(_httpClient);
      }
   }
}
