//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Substrate.Astar.NET.RestClient
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Substrate.Astar.NET.RestClient.Generated.Interfaces;
   using Substrate.Astar.NET.RestClient.Generated.Clients;
   
   public sealed class Client
   {
      private HttpClient _httpClient;
      private BaseSubscriptionClient _subscriptionClient;
      public IAssetsControllerClient AssetsControllerClient;
      public IAuraControllerClient AuraControllerClient;
      public IAuraExtControllerClient AuraExtControllerClient;
      public IAuthorshipControllerClient AuthorshipControllerClient;
      public IBalancesControllerClient BalancesControllerClient;
      public IBaseFeeControllerClient BaseFeeControllerClient;
      public IBlockRewardControllerClient BlockRewardControllerClient;
      public ICollatorSelectionControllerClient CollatorSelectionControllerClient;
      public IContractsControllerClient ContractsControllerClient;
      public IDappsStakingControllerClient DappsStakingControllerClient;
      public IDmpQueueControllerClient DmpQueueControllerClient;
      public IEthereumControllerClient EthereumControllerClient;
      public IEVMControllerClient EVMControllerClient;
      public IIdentityControllerClient IdentityControllerClient;
      public IMultisigControllerClient MultisigControllerClient;
      public IParachainInfoControllerClient ParachainInfoControllerClient;
      public IParachainSystemControllerClient ParachainSystemControllerClient;
      public IPolkadotXcmControllerClient PolkadotXcmControllerClient;
      public ISessionControllerClient SessionControllerClient;
      public ISudoControllerClient SudoControllerClient;
      public ISystemControllerClient SystemControllerClient;
      public ITimestampControllerClient TimestampControllerClient;
      public ITransactionPaymentControllerClient TransactionPaymentControllerClient;
      public IVestingControllerClient VestingControllerClient;
      public IXcAssetConfigControllerClient XcAssetConfigControllerClient;
      public IXcmpQueueControllerClient XcmpQueueControllerClient;
      public Client(HttpClient httpClient, BaseSubscriptionClient subscriptionClient)
      {
         _httpClient = httpClient;
         _subscriptionClient = subscriptionClient;
         AssetsControllerClient = new AssetsControllerClient(_httpClient, _subscriptionClient);
         AuraControllerClient = new AuraControllerClient(_httpClient, _subscriptionClient);
         AuraExtControllerClient = new AuraExtControllerClient(_httpClient, _subscriptionClient);
         AuthorshipControllerClient = new AuthorshipControllerClient(_httpClient, _subscriptionClient);
         BalancesControllerClient = new BalancesControllerClient(_httpClient, _subscriptionClient);
         BaseFeeControllerClient = new BaseFeeControllerClient(_httpClient, _subscriptionClient);
         BlockRewardControllerClient = new BlockRewardControllerClient(_httpClient, _subscriptionClient);
         CollatorSelectionControllerClient = new CollatorSelectionControllerClient(_httpClient, _subscriptionClient);
         ContractsControllerClient = new ContractsControllerClient(_httpClient, _subscriptionClient);
         DappsStakingControllerClient = new DappsStakingControllerClient(_httpClient, _subscriptionClient);
         DmpQueueControllerClient = new DmpQueueControllerClient(_httpClient, _subscriptionClient);
         EthereumControllerClient = new EthereumControllerClient(_httpClient, _subscriptionClient);
         EVMControllerClient = new EVMControllerClient(_httpClient, _subscriptionClient);
         IdentityControllerClient = new IdentityControllerClient(_httpClient, _subscriptionClient);
         MultisigControllerClient = new MultisigControllerClient(_httpClient, _subscriptionClient);
         ParachainInfoControllerClient = new ParachainInfoControllerClient(_httpClient, _subscriptionClient);
         ParachainSystemControllerClient = new ParachainSystemControllerClient(_httpClient, _subscriptionClient);
         PolkadotXcmControllerClient = new PolkadotXcmControllerClient(_httpClient, _subscriptionClient);
         SessionControllerClient = new SessionControllerClient(_httpClient, _subscriptionClient);
         SudoControllerClient = new SudoControllerClient(_httpClient, _subscriptionClient);
         SystemControllerClient = new SystemControllerClient(_httpClient, _subscriptionClient);
         TimestampControllerClient = new TimestampControllerClient(_httpClient, _subscriptionClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerClient(_httpClient, _subscriptionClient);
         VestingControllerClient = new VestingControllerClient(_httpClient, _subscriptionClient);
         XcAssetConfigControllerClient = new XcAssetConfigControllerClient(_httpClient, _subscriptionClient);
         XcmpQueueControllerClient = new XcmpQueueControllerClient(_httpClient, _subscriptionClient);
      }
   }
}
