//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Substrate.Moonsama.NET.RestClient.Mockup
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Substrate.Moonsama.NET.RestClient.Mockup.Generated.Interfaces;
   using Substrate.Moonsama.NET.RestClient.Mockup.Generated.Clients;
   
   public sealed class MockupClient
   {
      private HttpClient _httpClient;
      public IAssetManagerControllerMockupClient AssetManagerControllerClient;
      public IAssetsControllerMockupClient AssetsControllerClient;
      public IAuraControllerMockupClient AuraControllerClient;
      public IAuraExtControllerMockupClient AuraExtControllerClient;
      public IAuthorshipControllerMockupClient AuthorshipControllerClient;
      public IBalancesControllerMockupClient BalancesControllerClient;
      public IContractsControllerMockupClient ContractsControllerClient;
      public ICrowdloanRewardsControllerMockupClient CrowdloanRewardsControllerClient;
      public IDmpQueueControllerMockupClient DmpQueueControllerClient;
      public IEthereumControllerMockupClient EthereumControllerClient;
      public IEvmChainIdControllerMockupClient EvmChainIdControllerClient;
      public IEVMControllerMockupClient EVMControllerClient;
      public IFreeCallsRegistryControllerMockupClient FreeCallsRegistryControllerClient;
      public IIdentityControllerMockupClient IdentityControllerClient;
      public ILocalAssetsControllerMockupClient LocalAssetsControllerClient;
      public IMaintenanceModeControllerMockupClient MaintenanceModeControllerClient;
      public IMintingControllerMockupClient MintingControllerClient;
      public IMultisigControllerMockupClient MultisigControllerClient;
      public IMultiTokenControllerMockupClient MultiTokenControllerClient;
      public IParachainInfoControllerMockupClient ParachainInfoControllerClient;
      public IParachainStakingControllerMockupClient ParachainStakingControllerClient;
      public IParachainSystemControllerMockupClient ParachainSystemControllerClient;
      public IPreimageControllerMockupClient PreimageControllerClient;
      public IProxyControllerMockupClient ProxyControllerClient;
      public IRandomnessControllerMockupClient RandomnessControllerClient;
      public IRolesManagementControllerMockupClient RolesManagementControllerClient;
      public ISchedulerControllerMockupClient SchedulerControllerClient;
      public ISessionControllerMockupClient SessionControllerClient;
      public ISudoControllerMockupClient SudoControllerClient;
      public ISystemControllerMockupClient SystemControllerClient;
      public ITimestampControllerMockupClient TimestampControllerClient;
      public ITransactionPaymentControllerMockupClient TransactionPaymentControllerClient;
      public ITreasuryControllerMockupClient TreasuryControllerClient;
      public IXcmpQueueControllerMockupClient XcmpQueueControllerClient;
      public IXTokensControllerMockupClient XTokensControllerClient;
      public MockupClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
         AssetManagerControllerClient = new AssetManagerControllerMockupClient(_httpClient);
         AssetsControllerClient = new AssetsControllerMockupClient(_httpClient);
         AuraControllerClient = new AuraControllerMockupClient(_httpClient);
         AuraExtControllerClient = new AuraExtControllerMockupClient(_httpClient);
         AuthorshipControllerClient = new AuthorshipControllerMockupClient(_httpClient);
         BalancesControllerClient = new BalancesControllerMockupClient(_httpClient);
         ContractsControllerClient = new ContractsControllerMockupClient(_httpClient);
         CrowdloanRewardsControllerClient = new CrowdloanRewardsControllerMockupClient(_httpClient);
         DmpQueueControllerClient = new DmpQueueControllerMockupClient(_httpClient);
         EthereumControllerClient = new EthereumControllerMockupClient(_httpClient);
         EvmChainIdControllerClient = new EvmChainIdControllerMockupClient(_httpClient);
         EVMControllerClient = new EVMControllerMockupClient(_httpClient);
         FreeCallsRegistryControllerClient = new FreeCallsRegistryControllerMockupClient(_httpClient);
         IdentityControllerClient = new IdentityControllerMockupClient(_httpClient);
         LocalAssetsControllerClient = new LocalAssetsControllerMockupClient(_httpClient);
         MaintenanceModeControllerClient = new MaintenanceModeControllerMockupClient(_httpClient);
         MintingControllerClient = new MintingControllerMockupClient(_httpClient);
         MultisigControllerClient = new MultisigControllerMockupClient(_httpClient);
         MultiTokenControllerClient = new MultiTokenControllerMockupClient(_httpClient);
         ParachainInfoControllerClient = new ParachainInfoControllerMockupClient(_httpClient);
         ParachainStakingControllerClient = new ParachainStakingControllerMockupClient(_httpClient);
         ParachainSystemControllerClient = new ParachainSystemControllerMockupClient(_httpClient);
         PreimageControllerClient = new PreimageControllerMockupClient(_httpClient);
         ProxyControllerClient = new ProxyControllerMockupClient(_httpClient);
         RandomnessControllerClient = new RandomnessControllerMockupClient(_httpClient);
         RolesManagementControllerClient = new RolesManagementControllerMockupClient(_httpClient);
         SchedulerControllerClient = new SchedulerControllerMockupClient(_httpClient);
         SessionControllerClient = new SessionControllerMockupClient(_httpClient);
         SudoControllerClient = new SudoControllerMockupClient(_httpClient);
         SystemControllerClient = new SystemControllerMockupClient(_httpClient);
         TimestampControllerClient = new TimestampControllerMockupClient(_httpClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerMockupClient(_httpClient);
         TreasuryControllerClient = new TreasuryControllerMockupClient(_httpClient);
         XcmpQueueControllerClient = new XcmpQueueControllerMockupClient(_httpClient);
         XTokensControllerClient = new XTokensControllerMockupClient(_httpClient);
      }
   }
}
