//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Substrate.Collectives.NET.RestClient
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Substrate.Collectives.NET.RestClient.Generated.Interfaces;
   using Substrate.Collectives.NET.RestClient.Generated.Clients;
   
   public sealed class Client
   {
      private HttpClient _httpClient;
      private BaseSubscriptionClient _subscriptionClient;
      public IAllianceControllerClient AllianceControllerClient;
      public IAllianceMotionControllerClient AllianceMotionControllerClient;
      public IAmbassadorCollectiveControllerClient AmbassadorCollectiveControllerClient;
      public IAmbassadorCoreControllerClient AmbassadorCoreControllerClient;
      public IAmbassadorReferendaControllerClient AmbassadorReferendaControllerClient;
      public IAmbassadorSalaryControllerClient AmbassadorSalaryControllerClient;
      public IAmbassadorTreasuryControllerClient AmbassadorTreasuryControllerClient;
      public IAssetRateControllerClient AssetRateControllerClient;
      public IAuraControllerClient AuraControllerClient;
      public IAuraExtControllerClient AuraExtControllerClient;
      public IAuthorshipControllerClient AuthorshipControllerClient;
      public IBalancesControllerClient BalancesControllerClient;
      public ICollatorSelectionControllerClient CollatorSelectionControllerClient;
      public IFellowshipCollectiveControllerClient FellowshipCollectiveControllerClient;
      public IFellowshipCoreControllerClient FellowshipCoreControllerClient;
      public IFellowshipReferendaControllerClient FellowshipReferendaControllerClient;
      public IFellowshipSalaryControllerClient FellowshipSalaryControllerClient;
      public IFellowshipTreasuryControllerClient FellowshipTreasuryControllerClient;
      public IMessageQueueControllerClient MessageQueueControllerClient;
      public IMultisigControllerClient MultisigControllerClient;
      public IParachainInfoControllerClient ParachainInfoControllerClient;
      public IParachainSystemControllerClient ParachainSystemControllerClient;
      public IPolkadotXcmControllerClient PolkadotXcmControllerClient;
      public IPreimageControllerClient PreimageControllerClient;
      public IProxyControllerClient ProxyControllerClient;
      public ISchedulerControllerClient SchedulerControllerClient;
      public ISessionControllerClient SessionControllerClient;
      public ISystemControllerClient SystemControllerClient;
      public ITimestampControllerClient TimestampControllerClient;
      public ITransactionPaymentControllerClient TransactionPaymentControllerClient;
      public IXcmpQueueControllerClient XcmpQueueControllerClient;
      public Client(HttpClient httpClient, BaseSubscriptionClient subscriptionClient)
      {
         _httpClient = httpClient;
         _subscriptionClient = subscriptionClient;
         AllianceControllerClient = new AllianceControllerClient(_httpClient, _subscriptionClient);
         AllianceMotionControllerClient = new AllianceMotionControllerClient(_httpClient, _subscriptionClient);
         AmbassadorCollectiveControllerClient = new AmbassadorCollectiveControllerClient(_httpClient, _subscriptionClient);
         AmbassadorCoreControllerClient = new AmbassadorCoreControllerClient(_httpClient, _subscriptionClient);
         AmbassadorReferendaControllerClient = new AmbassadorReferendaControllerClient(_httpClient, _subscriptionClient);
         AmbassadorSalaryControllerClient = new AmbassadorSalaryControllerClient(_httpClient, _subscriptionClient);
         AmbassadorTreasuryControllerClient = new AmbassadorTreasuryControllerClient(_httpClient, _subscriptionClient);
         AssetRateControllerClient = new AssetRateControllerClient(_httpClient, _subscriptionClient);
         AuraControllerClient = new AuraControllerClient(_httpClient, _subscriptionClient);
         AuraExtControllerClient = new AuraExtControllerClient(_httpClient, _subscriptionClient);
         AuthorshipControllerClient = new AuthorshipControllerClient(_httpClient, _subscriptionClient);
         BalancesControllerClient = new BalancesControllerClient(_httpClient, _subscriptionClient);
         CollatorSelectionControllerClient = new CollatorSelectionControllerClient(_httpClient, _subscriptionClient);
         FellowshipCollectiveControllerClient = new FellowshipCollectiveControllerClient(_httpClient, _subscriptionClient);
         FellowshipCoreControllerClient = new FellowshipCoreControllerClient(_httpClient, _subscriptionClient);
         FellowshipReferendaControllerClient = new FellowshipReferendaControllerClient(_httpClient, _subscriptionClient);
         FellowshipSalaryControllerClient = new FellowshipSalaryControllerClient(_httpClient, _subscriptionClient);
         FellowshipTreasuryControllerClient = new FellowshipTreasuryControllerClient(_httpClient, _subscriptionClient);
         MessageQueueControllerClient = new MessageQueueControllerClient(_httpClient, _subscriptionClient);
         MultisigControllerClient = new MultisigControllerClient(_httpClient, _subscriptionClient);
         ParachainInfoControllerClient = new ParachainInfoControllerClient(_httpClient, _subscriptionClient);
         ParachainSystemControllerClient = new ParachainSystemControllerClient(_httpClient, _subscriptionClient);
         PolkadotXcmControllerClient = new PolkadotXcmControllerClient(_httpClient, _subscriptionClient);
         PreimageControllerClient = new PreimageControllerClient(_httpClient, _subscriptionClient);
         ProxyControllerClient = new ProxyControllerClient(_httpClient, _subscriptionClient);
         SchedulerControllerClient = new SchedulerControllerClient(_httpClient, _subscriptionClient);
         SessionControllerClient = new SessionControllerClient(_httpClient, _subscriptionClient);
         SystemControllerClient = new SystemControllerClient(_httpClient, _subscriptionClient);
         TimestampControllerClient = new TimestampControllerClient(_httpClient, _subscriptionClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerClient(_httpClient, _subscriptionClient);
         XcmpQueueControllerClient = new XcmpQueueControllerClient(_httpClient, _subscriptionClient);
      }
   }
}
