//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Substrate.Coretime.NET.RestClient.Mockup
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Substrate.Coretime.NET.RestClient.Mockup.Generated.Interfaces;
   using Substrate.Coretime.NET.RestClient.Mockup.Generated.Clients;
   
   public sealed class MockupClient
   {
      private HttpClient _httpClient;
      public IAuraControllerMockupClient AuraControllerClient;
      public IAuraExtControllerMockupClient AuraExtControllerClient;
      public IAuthorshipControllerMockupClient AuthorshipControllerClient;
      public IBalancesControllerMockupClient BalancesControllerClient;
      public IBrokerControllerMockupClient BrokerControllerClient;
      public ICollatorSelectionControllerMockupClient CollatorSelectionControllerClient;
      public IMessageQueueControllerMockupClient MessageQueueControllerClient;
      public IMultisigControllerMockupClient MultisigControllerClient;
      public IParachainInfoControllerMockupClient ParachainInfoControllerClient;
      public IParachainSystemControllerMockupClient ParachainSystemControllerClient;
      public IPolkadotXcmControllerMockupClient PolkadotXcmControllerClient;
      public IProxyControllerMockupClient ProxyControllerClient;
      public ISessionControllerMockupClient SessionControllerClient;
      public ISystemControllerMockupClient SystemControllerClient;
      public ITimestampControllerMockupClient TimestampControllerClient;
      public ITransactionPaymentControllerMockupClient TransactionPaymentControllerClient;
      public IXcmpQueueControllerMockupClient XcmpQueueControllerClient;
      public MockupClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
         AuraControllerClient = new AuraControllerMockupClient(_httpClient);
         AuraExtControllerClient = new AuraExtControllerMockupClient(_httpClient);
         AuthorshipControllerClient = new AuthorshipControllerMockupClient(_httpClient);
         BalancesControllerClient = new BalancesControllerMockupClient(_httpClient);
         BrokerControllerClient = new BrokerControllerMockupClient(_httpClient);
         CollatorSelectionControllerClient = new CollatorSelectionControllerMockupClient(_httpClient);
         MessageQueueControllerClient = new MessageQueueControllerMockupClient(_httpClient);
         MultisigControllerClient = new MultisigControllerMockupClient(_httpClient);
         ParachainInfoControllerClient = new ParachainInfoControllerMockupClient(_httpClient);
         ParachainSystemControllerClient = new ParachainSystemControllerMockupClient(_httpClient);
         PolkadotXcmControllerClient = new PolkadotXcmControllerMockupClient(_httpClient);
         ProxyControllerClient = new ProxyControllerMockupClient(_httpClient);
         SessionControllerClient = new SessionControllerMockupClient(_httpClient);
         SystemControllerClient = new SystemControllerMockupClient(_httpClient);
         TimestampControllerClient = new TimestampControllerMockupClient(_httpClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerMockupClient(_httpClient);
         XcmpQueueControllerClient = new XcmpQueueControllerMockupClient(_httpClient);
      }
   }
}
