name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build & test
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
        with:
        # Set the version of Node.js to use to v16
          node-version: '16.x'
          
      ##
      # Setup
      # Setup multiple .NET versions so we can build against all referenced .NET versions.
      ##
      - name: Setup .NET Core 2.1.x
        uses: actions/setup-dotnet@v1.4.4
        with:
          node-version: '16.x'
          dotnet-version: 2.1.x
     
      - name: Setup .NET Core 3.1.x
        uses: actions/setup-dotnet@v1.4.4
        with:
          node-version: '16.x'
          dotnet-version: 3.1.x

      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          node-version: '16.x'
          dotnet-version: 6.0.x

      - name: Setup .NET 7.0.x
        uses: actions/setup-dotnet@v2
        with:
          node-version: '16.x'
          dotnet-version: 7.0.x
      
      ##
      # Dependencies
      # Restore the project and its dependencies.
      ##
      - name: Install dependencies
        run: dotnet restore Substrate.Ajuna.NET
      
      #
      # Build
      # Build the toolchain
      ##
      - name: Build
        run: |
            dotnet build Substrate.Ajuna.NET --configuration Release
            
